# https://hub.docker.com/_/postgres
version: '3.9'

services:

  db:
    image: postgres:15.3-alpine3.18
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "pizza_db"
      POSTGRES_USER: "pizza_user"
      POSTGRES_PASSWORD: "secret"