name: "Run tests to template"
on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: gradle-test
        run: ./gradlew test
